### PR TITLE
First try at meson.build for Lua 5.1.

### PR DESCRIPTION
**Pull request by averms**
This is my first try at writing a robust meson build script for Lua 5.1.5. Although this version isn't really maintained anymore, it is still widely used  \[1] \[2] \[3] and fairly bug-free (minus a few small things that can be patched).

[1]\: https://github.com/redis/redis
[2]\: https://github.com/neovim/neovim
[3]\: https://github.com/davidgiven/wordgrinder

### CODE REVIEW

**Comment by eli-schwartz** [comment]
What's the utility in adding an old version when people can/should just use the newer version?

Is there some project using meson that specifically needs 5.1, or is this just a general "people use it in ways that don't matter here" sort of thing?

**Comment by averms** [comment]
I already made the build script for my own projects and I thought, why not submit it?

> Is there some project using meson that specifically needs 5.1

If the only things packaged for wrapdb are libraries people are already using, you're going to have a chicken and egg problem

**Comment by eli-schwartz** [comment]
> If the only things packaged for wrapdb are libraries people are already using

No one ever said that...

The meson wrapdb doesn't particularly desire, however, to fill up with old versions of something already packaged with an older version. So I was wondering if you had some out of the ordinary reason.

It's not entirely clear to me why meson projects adding lua support today, would opt for the lua version released in 2006 rather than the one released in 2015.

Actually, it's not clear to me why anyone would do so for *any* reason, on actively maintained code, including code that is being ported to meson. Lua upstream dropped support for 5.1 in the year 2012, so it's now abandoned for nearly a decade.

**Comment by jpakkane** [comment]
If someone has real use for such an old version, then we can consider adding it. However as noted above, this version has been out of support for 8 years so this seems unlikely.

I'm going to close this MR for now. If there is an actual use case, feel free to reopen with details on the usage.

Thanks.

**Pull request closed without merging**
